const CharacterTypes = {
  FETCH_CHARACTERS_PENDING: 'FETCH_CHARACTERS_PENDING',
  FETCH_CHARACTERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_FAIL: 'FETCH_CHARACTERS_FAIL',
  GET_CHARACTER: 'GET_CHARACTER',
  SEARCH_CHARACTER: 'SEARCH_CHARACTER',
  SEARCH_CHARACTER_CLEAR: 'SEARCH_CHARACTER_CLEAR',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
};
export default CharacterTypes;
