const CharacterTypes = {
  FETCH_CHARACTERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_FAIL: 'FETCH_CHARACTERS_FAIL',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
};
export default CharacterTypes;
