const LocationTypes = {
  FETCH_LOCATIONS_SUCCESS: 'FETCH_LOCATIONS_SUCCESS',
  FETCH_LOCATIONS_FAIL: 'FETCH_LOCATIONS_FAIL',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_RESIDENTS: 'SET_RESIDENTS',
  REFRESH: 'REFRESH',
};
export default LocationTypes;
